### PR TITLE
Assortment of fixes

### PR DESCRIPTION
**Pull request by mundschenk-at**
* Adds an additional program type `4` necessary for the washer-dryer (apparently identical to `3`).
* Handles `0` as program ID for dishwashers (similar to program phases).
* Improves consistency of the German translation.
* Marks the `programType`sensor as diagnostic – there's not much information in there (as opposed to the `programID`).

### CODE REVIEW

**Review by astrandb — CHANGES_REQUESTED** [review]
We should have unified handling of tabs/indents or we will get lots of unnecessary changes.
I use vscode with Prettier installed. It does some basic reformatting when saving files.
My defaults are tab=4 spaces in python code, and tab=2 spaces in json files. Your editor seems to use tab characters in json files.
I don't know when all tabs sneaked in but they should be removed IMHO.

**Comment by mundschenk-at** [comment]
> We should have unified handling of tabs/indents or we will get lots of unnecessary changes.
> I use vscode with Prettier installed. It does some basic reformatting when saving files.
> My defaults are tab=4 spaces in python code, and tab=2 spaces in json files. Your editor seems to use tab characters in json files.
> I don't know when all tabs sneaked in but they should be removed IMHO.

I am using Atom but I haven't really set up a additional defaults, so it should stick to what the file already was. There was an issue with the original commit for the JSON files I couldn't find at 3 in the morning, so I just used the pretty printer. I didn't realise it had changed the spaces to tabs, but I saw that there were whitespace changes. I'll change the JSON files back to tabs in this branch.

**Comment by mundschenk-at** [comment]
How about adding a prettier (and what other linters are useful for other file types) configuration to the repo?

**Review by astrandb — APPROVED** [review]
Looks good!

**Pull request merged**
