### PR TITLE
Add microwave support

### PR DESCRIPTION
**Pull request by principis**
This adds support for microwaves. Microwave mappings are in the same set as ovens, so I combined them. I can add more program phases, but these are the ones I've used so far.

_I may start a war because of the Dutch translation, but oh well I was first and there is no way to accommodate everyone._ :sweat_smile:

### CODE REVIEW

**Comment by aturri** [comment]
Italian translation is ok! 👍

**Comment by principis** [comment]
@aturri could you translate the `energy_save` string to Italian? In the Miele app it's actually "Energy save phase" which makes it difficult to translate, since we use just "Energy save". If it helps, the Miele translation is `Fase risparmio energetico`.

**Review by astrandb — APPROVED** [review]
Looks good, thank you!

**Comment by aturri** [comment]
> @aturri could you translate the `energy_save` string to Italian? In the Miele app it's actually "Energy save phase" which makes it difficult to translate, since we use just "Energy save". If it helps, the Miele translation is `Fase risparmio energetico`.

Yeah, `Fase risparmio energetico` is good :) 
Thanks!

**Pull request merged**
