### PR TITLE
Add large_pillows tumble dryer program

### PR DESCRIPTION
**Pull request by apeeters**
Required for full TCR790WP mapping.

### CODE REVIEW

**Comment by astrandb** [comment]
We need the raw value presented by the API also. Please capture a diagnostic download from the device page when running the large pillows program.

**Comment by aturri** [comment]
Hi, it's mapped on 20, so it is in conflict with an existing program.

**Comment by astrandb** [comment]
Stale. closing

**Comment by apeeters** [comment]
@astrandb this issue is still valid. As @aturri mentioned, the raw value is 20:
```
      "state|ProgramID|value_raw": 20,
      "state|ProgramID|value_localized": "Large pillows",
      "state|ProgramID|key_localized": "Program name",
```
Which indeed conflicts with the existing cottons program. This is why the `unmapped_5` entry is needed: to allow [local Localization override](https://github.com/astrandb/miele/wiki/Localization).

**Review by astrandb — CHANGES_REQUESTED** [review]
I am sorry that this PR has been forgotten.

`"large_pillows": "Large pillows",` should be added to translations/en.json
The other languages will be handled in Lokalise by our team of translators.

**Review by astrandb — APPROVED** [review]
Thank you, @apeeters .

**Pull request merged**
