### PR TITLE
PR sent with Spanish translation

### PR DESCRIPTION
**Pull request by cvc90**
PR is sent with translation into Spanish, attached validation image of .json file

image

### CODE REVIEW

**Comment by astrandb** [comment]
Thank you for your contribution. 
Translations are handled in Lokalise, Please see https://github.com/astrandb/miele?tab=readme-ov-file#translation
I have uploaded your es.json to Lokalise. Please review the translation there and make corrections, if any, in the UI.
The spanish translation will be included in next release of the integration.

**Comment by cvc90** [comment]
Hi @astrandb,

When do you plan to release the next version? 😄

**Comment by astrandb** [comment]
Very soon, within a day or two. 😄

**Comment by astrandb** [comment]
Closing this PR since the spanish translation is now managed by Lokalise. Thank you for submitting the initial es.json.

**Pull request closed without merging**
